version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: product table of Greenweez
        columns:
        - name: products_id
          tests:
            - unique
            - not_null
        - name: purchSE_PRICE
          tests:
            - not_null
      - name: sales
        identifier: raw_gz_sales
        description: sales table of Greenweez
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity
      - name: ship
        identifier: raw_gz_ship
        description: ship table of Greenweez
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost
                
